name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: release
    env:
      GITHUB_REF_NAME: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x
      - name: Add source
        run: dotnet nuget add source --username USERNAME --password ${{ secrets.NUGET_TOKEN  }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ vars.NAMESPACE }}/index.json"
      - name: Restore dependencies
        run: dotnet restore
      - name: Pack
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          dotnet pack "./src/HoYoLab/HoYoLab.csproj" --configuration Release -p:Version=$VERSION
      - name: Publish
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          dotnet nuget push "./src/HoYoLab/bin/Release/HoYoLab.$VERSION.nupkg" --source "github"
